version: '2'
services:
  fleet-boot-mysql:
    build:
      context: ../db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: fleet-boot-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306

  fleet-boot-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: fleet-boot-redis
    hostname: fleet-boot-redis

  fleet-boot-nacos:
    restart: on-failure
    build:
      context: ./fleet-cloud-nacos
    ports:
      - 8848:8848
    depends_on:
      - fleet-boot-mysql
    container_name: fleet-boot-nacos
    hostname: fleet-boot-nacos

  fleet-boot-gateway:
    restart: on-failure
    build:
      context: ./fleet-cloud-gateway
    ports:
      - 9999:9999
    depends_on:
      - fleet-boot-nacos
      - fleet-boot-redis
    container_name: fleet-boot-gateway
    hostname: fleet-boot-gateway

  fleet-boot-system:
    depends_on:
      - fleet-boot-mysql
      - fleet-boot-redis
      - fleet-boot-nacos
    build:
      context: ./fleet-cloud-system-start
    container_name: fleet-boot-system
    hostname: fleet-boot-system
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai

#  fleet-boot-xxljob:
#    build:
#      context: ./fleet-cloud-xxljob
#    ports:
#      - 9080:9080
#    container_name: fleet-boot-xxljob
#    hostname: fleet-boot-xxljob

#  fleet-boot-rabbitmq:
#    #    image: rabbitmq:3-management
#    image: rabbitmq:3
#    ports:
#      - 5672:5672
#    #      - 15672:15672
#    restart: always
#    container_name: fleet-boot-rabbitmq
#    hostname: fleet-boot-rabbitmq
